name: education
description: An educational project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
 
  adaptive_theme: ^3.2.1
  flutter_animate: ^4.1.1+1
  fluttertoast: ^8.2.2
  font_awesome_flutter: ^10.4.0
  get: ^4.6.5
  google_fonts: ^4.0.5
  flutter_animated_button: ^2.0.3
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  intl: ^0.18.1
  lottie: ^2.3.2
  url_strategy: ^0.2.0
  cloud_firestore: ^4.7.1
  firebase_auth: ^4.6.1
  firebase_core: ^2.13.0
  intl_phone_field: ^3.1.0
  google_sign_in: ^5.4.4
 
dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^2.0.0

flutter:

 
  uses-material-design: true
  assets:
   - assets/
   - assets/lottie/
  

 
  
